packages:
  - packages/*

catalog:
  '@arethetypeswrong/core': ^0.18.2
  '@babel/code-frame': ^7.29.0
  '@babel/core': ^7.29.0
  '@babel/helper-module-imports': ^7.28.6
  '@babel/helper-plugin-utils': ^7.28.6
  '@babel/parser': ^7.29.3
  '@babel/plugin-syntax-jsx': ^7.28.6
  '@babel/plugin-syntax-typescript': ^7.28.6
  '@babel/preset-env': ^7.29.3
  '@babel/standalone': ^7.29.3
  '@babel/template': ^7.28.6
  '@babel/traverse': ^7.29.0
  '@babel/types': ^7.29.0
  '@rollup/plugin-babel': ^7.0.0
  '@sxzz/eslint-config': ^8.0.0
  '@sxzz/prettier-config': ^2.3.1
  '@types/babel__code-frame': ^7.27.0
  '@types/babel__core': ^7.20.5
  '@types/babel__helper-module-imports': ^7.18.3
  '@types/babel__helper-plugin-utils': ^7.10.3
  '@types/babel__standalone': ^7.1.9
  '@types/babel__template': ^7.4.4
  '@types/babel__traverse': ^7.28.0
  '@types/node': ^25.6.0
  '@typescript/native-preview': 7.0.0-dev.20260501.1
  '@vitejs/plugin-vue-jsx': ^5.1.5
  '@vitest/coverage-v8': ^4.1.5
  '@vue/compiler-sfc': ^3.5.33
  '@vue/shared': ^3.5.33
  '@vue/test-utils': ^2.4.10
  assert: ^2.1.0
  bumpp: ^11.0.1
  eslint: ^10.3.0
  jsdom: ^29.1.1
  monaco-editor: ^0.55.1
  prettier: 3.8.3
  regenerator-runtime: ^0.14.1
  tsdown: ^0.21.10
  tslib: ^2.8.1
  typescript: ~6.0.3
  vite: ^8.0.10
  vitest: ^4.1.5
  vue: ^3.5.33

allowBuilds:
  esbuild: false

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 604800 # 7 days
