packages:
  - packages/*

catalog:
  '@arethetypeswrong/core': ^0.18.2
  '@babel/code-frame': ^8.0.0
  '@babel/core': ^8.0.0
  '@babel/helper-module-imports': ^8.0.0
  '@babel/helper-plugin-utils': ^8.0.0
  '@babel/parser': ^8.0.0
  '@babel/plugin-syntax-jsx': ^8.0.0
  '@babel/plugin-syntax-typescript': ^8.0.0
  '@babel/preset-env': ^8.0.0
  '@babel/standalone': ^8.0.0
  '@babel/template': ^8.0.0
  '@babel/types': ^8.0.0
  '@rollup/plugin-babel': ^7.0.0
  '@sxzz/eslint-config': ^8.0.0
  '@sxzz/prettier-config': ^2.3.1
  '@types/babel__standalone': ^7.1.9
  '@types/node': ^25.6.0
  '@typescript/native-preview': 7.0.0-dev.20260501.1
  '@vitejs/plugin-vue-jsx': ^5.1.5
  '@vitest/coverage-v8': ^4.1.5
  '@vue/compiler-sfc': ^3.5.33
  '@vue/shared': ^3.5.33
  '@vue/test-utils': ^2.4.10
  assert: ^2.1.0
  bumpp: ^11.0.1
  eslint: ^10.3.0
  jsdom: ^29.1.1
  monaco-editor: ^0.55.1
  prettier: 3.8.3
  publint: ^0.3.18
  regenerator-runtime: ^0.14.1
  tsdown: ^0.21.10
  tslib: ^2.8.1
  typescript: ~6.0.3
  vite: ^8.0.16
  vitest: ^4.1.5
  vue: ^3.5.33

allowBuilds:
  esbuild: false

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 604800 # 7 days
