packages:
  - packages/*

catalog:
  '@arethetypeswrong/core': ^0.18.5
  '@babel/code-frame': ^8.0.0
  '@babel/core': ^8.0.1
  '@babel/helper-module-imports': ^8.0.0
  '@babel/helper-plugin-utils': ^8.0.1
  '@babel/parser': ^8.0.4
  '@babel/plugin-syntax-jsx': ^8.0.1
  '@babel/plugin-syntax-typescript': ^8.0.3
  '@babel/preset-env': ^8.0.2
  '@babel/standalone': ^8.0.4
  '@babel/template': ^8.0.0
  '@babel/types': ^8.0.4
  '@rolldown/plugin-babel': ^0.2.3
  '@sxzz/eslint-config': ^8.3.2
  '@sxzz/prettier-config': ^2.3.2
  '@types/babel__standalone': ^7.1.9
  '@types/node': ^26.1.1
  '@typescript/native-preview': 7.0.0-dev.20260707.2
  '@vitejs/plugin-vue-jsx': ^5.1.6
  '@vitest/coverage-v8': ^4.1.10
  '@vue/compiler-sfc': ^3.5.40
  '@vue/shared': ^3.5.40
  '@vue/test-utils': ^2.4.11
  assert: ^2.1.0
  bumpp: ^12.0.0
  eslint: ^10.8.0
  jsdom: ^30.0.0
  monaco-editor: ^0.56.0
  prettier: 3.9.6
  publint: ^0.3.24
  regenerator-runtime: ^0.14.1
  tsdown: ^0.22.14
  tslib: ^2.8.1
  typescript: ~6.0.3
  vite: ^8.1.5
  vitest: ^4.1.10
  vue: ^3.5.40

minimumReleaseAge: 0
shellEmulator: true
trustLockfile: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080 # 7 days
