name: Publish Any Commit
on: [push, pull_request]

permissions: {}

jobs:
  release:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    uses: sxzz/workflows/.github/workflows/release-commit.yml@v1
    with:
      packages: "'./packages/*'"
      compact: true
